#!/usr/bin/env python3
# 生成 YMGUI 定点三角表 (COMMON/MATH/YMGUI_TrigData.c)
# 角度 0..359 度,sin/cos 放大 32768 (即 Q15 定点),整数查表,无 libm
import math, sys

SCALE = 32768
out = []
out.append('#include "YMGUI_Trig.h"')
out.append("")
out.append("/**")
out.append("  ***************************************************************************************************************************")
out.append("  *\t@FileName:    YMGUI_TrigData.c")
out.append("  *\t@Author:      yaomimaoren (generated by Demo/gen_trig.py)")
out.append("  *\t@Date:        2026-07-01")
out.append(f"  *\t@Description: 定点三角表 sin/cos,角度0..359,Q15(放大{SCALE})。画弧/旋转用,无 libm")
out.append("  *\t@Version:     1.0")
out.append("  ***************************************************************************************************************************")
out.append("  * Copyright (C), 2026-2036, YAOMI Tech. Co., Ltd.")
out.append("  ***************************************************************************************************************************/")
out.append("")
out.append("//sin(deg) * 32768,deg 0..359")
out.append("const int16 GY_SinTab[360] =")
out.append("{")
vals = [int(round(math.sin(math.radians(d)) * SCALE)) for d in range(360)]
# 32768 会溢出 int16,钳到 32767
vals = [32767 if v > 32767 else (-32768 if v < -32768 else v) for v in vals]
for i in range(0, 360, 12):
    row = ", ".join(f"{v:6d}" for v in vals[i:i+12])
    out.append(f"\t{row},")
out.append("};")
out.append("")
with open(sys.argv[1], "w") as f:
    f.write("\n".join(out))
print(f"wrote {sys.argv[1]}: 360 entries Q15")
