#!/usr/bin/env python3
"""Build and verify a relocatable native Linux YMGUI binary SDK."""
import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import tarfile
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / "build/_ymgui_sdk"
OUT = ROOT / "build/YMGUI_libs"


def run(args, log, cwd=ROOT, env=None, expect_failure=False):
    args = list(map(str, args))
    print("Running:", " ".join(args), flush=True)
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open("w") as stream:
        result = subprocess.run(args, cwd=cwd, env=env, stdout=stream, stderr=subprocess.STDOUT)
    if (result.returncode == 0) == expect_failure:
        raise RuntimeError(f"Unexpected exit {result.returncode}: {args}\n{log.read_text()[-6000:]}")


def copy(source, dest):
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dest)


def digest_files(paths):
    digest = hashlib.sha256()
    for path in sorted(paths):
        digest.update(str(path.relative_to(ROOT)).encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--without-sdl", action="store_true", help="Build core archives only; SDL2 is not required")
    parser.add_argument("--ymgre-dir", type=Path, help="YMGRE binary package cmake directory; validate its examples")
    parser.add_argument("--jobs", type=int, default=4)
    args = parser.parse_args()
    if args.jobs < 1:
        parser.error("--jobs must be positive")
    if platform.system() != "Linux":
        parser.error("currently supports native Linux only")
    if args.ymgre_dir and args.without_sdl:
        parser.error("YMGRE window validation requires SDL")
    for command in ("cmake", "ctest", "cc", "nm"):
        if not shutil.which(command):
            parser.error(f"missing command: {command}")
    if OUT.is_symlink() or (OUT.exists() and not (OUT / ".ymgui-sdk").is_file()):
        parser.error(f"refusing to replace unmanaged output: {OUT}")
    WORK.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    # Fixed binary configuration: do not silently inherit custom ABI flags.
    for name in ("CFLAGS", "CPPFLAGS", "LDFLAGS"):
        if env.get(name):
            parser.error(f"unset {name} before packaging the default binary SDK")
    with tempfile.TemporaryDirectory(prefix="package-", dir=WORK) as temp:
        stage = Path(temp) / "YMGUI_libs"
        stage.mkdir()
        (stage / ".ymgui-sdk").write_text("Generated by sdk/package.py\n")
        for depth in (16, 24):
            build = WORK / f"rgb{depth}"
            run(["cmake", "-S", ROOT / "sdk/library", "-B", build,
                 "-DCMAKE_BUILD_TYPE=Release", f"-DYMGUI_COLOR_DEPTH={depth}",
                 f"-DYMGUI_SDK_BUILD_SDL={'OFF' if args.without_sdl else 'ON'}"],
                WORK / f"configure{depth}.log", env=env)
            run(["cmake", "--build", build, f"-j{args.jobs}"], WORK / f"build{depth}.log", env=env)
            copy(build / "libymgui.a", stage / f"lib/libymgui_rgb{depth}.a")
            if not args.without_sdl:
                copy(build / "libymgui_sdl.a", stage / f"lib/libymgui_sdl_rgb{depth}.a")
            symbols = subprocess.check_output(["nm", "-u", str(build / "libymgui.a")], text=True)
            if "SDL_" in symbols:
                raise RuntimeError("core archive unexpectedly references SDL")
        for header in (ROOT / "YMGUI").rglob("*.h"):
            if header.name != "YMGUI_PluginInternal.h":
                copy(header, stage / "include/YMGUI" / header.relative_to(ROOT / "YMGUI"))
        copy(ROOT / "sdk/YMGUI_SDK_Config.h", stage / "include/YMGUI/CONFIG/YMGUI_SDK_Config.h")
        pubtype = stage / "include/YMGUI/CONFIG/YMGUI_PubType.h"
        pubtype.write_text(pubtype.read_text().replace("#define YMGUI_PUBTYPE_H", '#define YMGUI_PUBTYPE_H\n#include "YMGUI_SDK_Config.h"', 1))
        if not args.without_sdl:
            copy(ROOT / "SDL_LCD/SDL_LCD.h", stage / "include/SDL_LCD/SDL_LCD.h")
        copy(WORK / "rgb16/platform.cmake", stage / "cmake/platform.cmake")
        copy(ROOT / "sdk/YMGUIConfig.cmake", stage / "cmake/YMGUIConfig.cmake")
        for source in (ROOT / "sdk/examples").iterdir():
            if source.is_file():
                copy(source, stage / "examples" / source.name)
        for name in ("README.md", "MANUAL.md", "build_demos.sh"):
            copy(ROOT / "sdk" / name, stage / name)
        copy(ROOT / "LICENSE", stage / "LICENSE")
        copy(ROOT / "tools/gb2312_glyphs.bin", stage / "resources/gb2312_glyphs.bin")
        (stage / ".gitignore").write_text("examples-build*/\n*.ppm\n")
        # Build consumers from a relocated copy outside the repository.
        with tempfile.TemporaryDirectory(prefix="ymgui-sdk-check-") as relocated:
            standalone = Path(relocated) / "YMGUI_libs"
            shutil.copytree(stage, standalone)
            for depth in (16, 24):
                for windowed in (False, True) if not args.without_sdl else (False,):
                    tag = f"rgb{depth}-{'sdl' if windowed else 'core'}"
                    consumer = Path(relocated) / tag
                    run(["cmake", "-S", standalone / "examples", "-B", consumer,
                         f"-DYMGUI_COLOR_DEPTH={depth}", f"-DYMGUI_WITH_SDL={'ON' if windowed else 'OFF'}",
                         "-DCMAKE_BUILD_TYPE=Release"], WORK / f"consumer-{tag}.log")
                    run(["cmake", "--build", consumer, f"-j{args.jobs}"], WORK / f"consumer-build-{tag}.log")
                    run(["ctest", "--test-dir", consumer, "--output-on-failure"], stage / f"verification/{tag}.log")
                    for name in ("demo_sdk_minimal", "demo_sdk_window"):
                        if (consumer / name).is_file():
                            copy(consumer / name, stage / f"bin/rgb{depth}" / name)
            run(["cmake", "-S", standalone / "examples", "-B", Path(relocated) / "invalid-depth",
                 "-DYMGUI_COLOR_DEPTH=8"], stage / "verification/reject-depth.log", expect_failure=True)
            # The SDK must reject coordinate/layout ABI mismatch at compile time.
            for flag in ("-DYMGUI_COORD_32=1", "-DGY_INV_MAX=32", "-DYMGUI_COLOR_DEPTH=24"):
                run(["cc", "-x", "c", "-c", "/dev/null", "-include",
                     standalone / "include/YMGUI/CONFIG/YMGUI_PubType.h", flag,
                     "-o", Path(relocated) / "invalid.o"],
                    stage / f"verification/reject-{flag.split('=')[0][2:]}.log", expect_failure=True)
            if args.ymgre_dir:
                ymgre_dir = args.ymgre_dir.resolve()
                for bits in (16, 32):
                    consumer = Path(relocated) / f"ymgre{bits}"
                    run(["cmake", "-S", ymgre_dir.parent / "examples", "-B", consumer,
                         f"-DYMGRE_DIR={ymgre_dir}", f"-DYMGUI_DIR={standalone / 'cmake'}",
                         "-DYMGRE_WINDOWED_DEMOS=ON", f"-DYMGRE_INDEX_BITS={bits}",
                         "-DYMGUI_COLOR_DEPTH=16", "-DCMAKE_BUILD_TYPE=Release"], WORK / f"ymgre-configure{bits}.log")
                    run(["cmake", "--build", consumer, f"-j{args.jobs}"], WORK / f"ymgre-build{bits}.log")
                    run(["ctest", "--test-dir", consumer, "--output-on-failure"], stage / f"verification/ymgre-index{bits}.log")
        sources = [p for folder in ("YMGUI", "SDL_LCD", "sdk") for p in (ROOT / folder).rglob("*")
                   if p.is_file() and p.suffix in (".c", ".h", ".cmake", ".txt", ".py", ".md", ".sh")]
        info = {
            "built_at_utc": datetime.now(timezone.utc).isoformat(),
            "system": platform.system(), "machine": platform.machine(),
            "compiler": subprocess.check_output(["cc", "--version"], text=True).splitlines()[0],
            "build_type": "Release", "position_independent": True,
            "color_depths": [16, 24], "coordinate_bits": 16, "GY_INV_MAX": 16,
            "bundled_sdl_adapter": not args.without_sdl, "bundled_sdl2": False,
            "external_ymgre_validated": bool(args.ymgre_dir),
            "source_sha256": digest_files(sources),
            "git_head": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
            "source_includes_uncommitted_changes": bool(subprocess.check_output(
                ["git", "status", "--porcelain", "--", "YMGUI", "SDL_LCD", "sdk"], cwd=ROOT, text=True).strip()),
            "sdk_requires_library_source": False, "rebuild_command": "./sdk/build.sh",
        }
        (stage / "BUILD_INFO.json").write_text(json.dumps(info, ensure_ascii=False, indent=2) + "\n")
        (stage / "checksums.sha256").write_text("".join(
            hashlib.sha256(p.read_bytes()).hexdigest() + "  " + str(p.relative_to(stage)) + "\n"
            for p in sorted(stage.rglob("*")) if p.is_file() and p.name != "checksums.sha256"))
        # Publish only after all consumers and rejection checks succeed.
        if OUT.exists():
            shutil.rmtree(OUT)
        shutil.move(str(stage), OUT)
    archive = OUT.parent / f"YMGUI_libs-{platform.system().lower()}-{platform.machine()}.tar.gz"
    pending = archive.with_suffix(".tmp")
    with tarfile.open(pending, "w:gz") as bundle:
        bundle.add(OUT, arcname="YMGUI_libs")
    pending.replace(archive)
    checksum = hashlib.sha256(archive.read_bytes()).hexdigest()
    archive.with_name(archive.name + ".sha256").write_text(checksum + "  " + archive.name + "\n")
    print(f"SDK complete: {OUT}\nArchive: {archive}\nSHA256: {checksum}", flush=True)


if __name__ == "__main__":
    main()
