#!/usr/bin/env python3
"""Generate YMGUI IME dictionaries from Rime and wordfreq data."""

import argparse
import re
import struct
from pathlib import Path


def gb2312_codepoints(index_path):
    text = Path(index_path).read_text(encoding="utf-8")
    return {int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]{4})", text)}


def merge_entry(word, syllables, frequency, codepoints, chars, phrases, max_phrase_len):
    if not syllables or any(not syllable.isascii() or not syllable.isalpha()
                            for syllable in syllables):
        return "pinyin must contain ASCII letter-only syllables"
    if any(ord(char) not in codepoints for char in word):
        return "word contains characters outside the YMGUI GB2312 font index"
    if len(word) == 1 and len(syllables) == 1:
        key = (syllables[0].lower(), word)
        chars[key] = max(chars.get(key, 0), frequency)
        return None
    if 2 <= len(word) <= max_phrase_len and len(syllables) == len(word):
        syllables = [syllable.lower() for syllable in syllables]
        pinyin = "'".join(syllables)
        initials = "".join(syllable[0] for syllable in syllables)
        key = (pinyin, initials, word)
        phrases[key] = max(phrases.get(key, 0), frequency)
        return None
    return f"word length and syllable count must match (phrases: 2..{max_phrase_len} characters)"


def read_rime_dictionary(source, codepoints):
    chars = {}
    phrases = {}
    body = False
    with Path(source).open("r", encoding="utf-8") as stream:
        for line in stream:
            line = line.rstrip("\n")
            if not body:
                if line == "...":
                    body = True
                continue
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) < 3:
                continue
            word, syllables = fields[0], fields[1].split()
            try:
                frequency = max(int(fields[2]), 0)
            except ValueError:
                continue
            merge_entry(word, syllables, frequency, codepoints, chars, phrases, 8)
    return chars, phrases


def read_extra_dictionary(source, codepoints, chars, phrases):
    with Path(source).open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) != 3:
                raise ValueError(f"{source}:{line_number}: expected word<TAB>pinyin<TAB>frequency")
            word = fields[0].strip()
            syllables = fields[1].replace("'", " ").split()
            try:
                frequency = int(fields[2])
            except ValueError as error:
                raise ValueError(f"{source}:{line_number}: frequency must be an integer") from error
            if frequency < 0 or frequency > 0xFFFFFFFF:
                raise ValueError(f"{source}:{line_number}: frequency must be in 0..4294967295")
            error = merge_entry(word, syllables, frequency, codepoints, chars, phrases, 31)
            if error:
                raise ValueError(f"{source}:{line_number}: {error}")


def char_rows(entries):
    rows = sorted(((pinyin, char, frequency) for (pinyin, char), frequency in entries.items()),
                  key=lambda item: (item[0], -item[2], item[1]))
    return rows


def char_bucket_offsets(rows):
    bucket_offsets = []
    cursor = 0
    for letter in "abcdefghijklmnopqrstuvwxyz":
        bucket_offsets.append(cursor)
        while cursor < len(rows) and rows[cursor][0][0] == letter:
            cursor += 1
    bucket_offsets.append(cursor)
    if cursor != len(rows):
        raise ValueError("character pinyin must start with an ASCII lowercase letter")
    return bucket_offsets


def write_chars(rows, output):
    bucket_offsets = char_bucket_offsets(rows)
    with Path(output).open("w", encoding="utf-8") as stream:
        stream.write("/* Generated by tools/gen_ime_dict.py from rime-pinyin-simp. */\n")
        stream.write("static const ImeCharEntry s_full_dict[] = {\n")
        for pinyin, char, frequency in rows:
            stream.write(f'    {{"{pinyin}", "{char}", {frequency}u}},\n')
        stream.write("};\n")
        stream.write("#define S_FULL_DICT_COUNT ((int)(sizeof(s_full_dict) / sizeof(s_full_dict[0])))\n")
        stream.write("static const uint32 s_char_buckets[27] = {\n    ")
        stream.write(", ".join(f"{offset}u" for offset in bucket_offsets))
        stream.write("\n};\n")


def write_char_binary(rows, output):
    blob = bytearray()
    records = []
    offsets = {}

    def add_string(value):
        encoded = value.encode("utf-8") + b"\0"
        if encoded not in offsets:
            offsets[encoded] = len(blob)
            blob.extend(encoded)
        return offsets[encoded]

    for pinyin, char, frequency in rows:
        records.append((add_string(pinyin), add_string(char), frequency))
    bucket_offsets = char_bucket_offsets(rows)
    header_size = 28 + len(bucket_offsets) * 4
    with Path(output).open("wb") as stream:
        stream.write(struct.pack("<8sIIIII", b"YMIMEC1\0", len(records), len(blob),
                                 header_size, 12, 26))
        stream.write(struct.pack("<27I", *bucket_offsets))
        for record in records:
            stream.write(struct.pack("<III", *record))
        stream.write(blob)


def phrase_rows(entries, limit):
    rows = [(frequency, pinyin, initials, word)
            for (pinyin, initials, word), frequency in entries.items()]
    if limit > 0:
        rows.sort(reverse=True)
        rows = rows[:limit]
    rows.sort(key=lambda row: (row[1][0], -row[0], row[1], row[2], row[3]))
    return rows


def phrase_bucket_offsets(rows):
    offsets = []
    cursor = 0
    for letter in "abcdefghijklmnopqrstuvwxyz":
        offsets.append(cursor)
        while cursor < len(rows) and rows[cursor][1][0] == letter:
            cursor += 1
    offsets.append(cursor)
    if cursor != len(rows):
        raise ValueError("phrase pinyin must start with an ASCII lowercase letter")
    return offsets


def write_phrases(rows, output):
    bucket_offsets = phrase_bucket_offsets(rows)
    with Path(output).open("w", encoding="utf-8") as stream:
        stream.write("/* Generated by tools/gen_ime_dict.py from rime-pinyin-simp. */\n")
        stream.write("static const PhraseEntry s_phrases[] = {\n")
        for frequency, pinyin, initials, word in rows:
            stream.write(f'    {{"{pinyin}", "{initials}", "{word}", {frequency}u}},\n')
        stream.write("};\n")
        stream.write("#define S_PHRASE_COUNT ((int)(sizeof(s_phrases) / sizeof(s_phrases[0])))\n")
        stream.write("static const uint32 s_phrase_buckets[27] = {\n    ")
        stream.write(", ".join(f"{offset}u" for offset in bucket_offsets))
        stream.write("\n};\n")


def write_phrase_binary(rows, output):
    blob = bytearray()
    records = []
    offsets = {}

    def add_string(value):
        encoded = value.encode("utf-8") + b"\0"
        if encoded not in offsets:
            offsets[encoded] = len(blob)
            blob.extend(encoded)
        return offsets[encoded]

    for frequency, pinyin, initials, word in rows:
        records.append((add_string(pinyin), add_string(initials), add_string(word), frequency))
    bucket_offsets = phrase_bucket_offsets(rows)
    header_size = 28 + len(bucket_offsets) * 4
    with Path(output).open("wb") as stream:
        stream.write(struct.pack("<8sIIIII", b"YMIMEP2\0", len(records), len(blob),
                                 header_size, 16, 26))
        stream.write(struct.pack("<27I", *bucket_offsets))
        for record in records:
            stream.write(struct.pack("<IIII", *record))
        stream.write(blob)


def english_rows(wordlist):
    try:
        from wordfreq import iter_wordlist
    except ImportError as error:
        raise RuntimeError("English generation requires: python3 -m pip install wordfreq") from error
    words = []
    seen = set()
    for word in iter_wordlist("en", wordlist=wordlist):
        if not (1 < len(word) <= 31 and word.isascii() and word.isalpha() and word.islower()):
            continue
        if word not in seen:
            seen.add(word)
            words.append(word)
    count = len(words)
    rows = [(count - rank, word) for rank, word in enumerate(words)]
    rows.sort(key=lambda row: (row[1][0], -row[0], row[1]))
    return rows


def english_bucket_offsets(rows):
    offsets = []
    cursor = 0
    for letter in "abcdefghijklmnopqrstuvwxyz":
        offsets.append(cursor)
        while cursor < len(rows) and rows[cursor][1][0] == letter:
            cursor += 1
    offsets.append(cursor)
    if cursor != len(rows):
        raise ValueError("English words must start with an ASCII lowercase letter")
    return offsets


def write_english_binary(rows, output):
    blob = bytearray()
    records = []
    for frequency, word in rows:
        offset = len(blob)
        blob.extend(word.encode("ascii") + b"\0")
        records.append((offset, frequency))
    bucket_offsets = english_bucket_offsets(rows)
    header_size = 28 + len(bucket_offsets) * 4
    with Path(output).open("wb") as stream:
        stream.write(struct.pack("<8sIIIII", b"YMIMEE1\0", len(records), len(blob),
                                 header_size, 8, 26))
        stream.write(struct.pack("<27I", *bucket_offsets))
        for record in records:
            stream.write(struct.pack("<II", *record))
        stream.write(blob)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rime-dict", required=True, help="rime-pinyin-simp pinyin_simp.dict.yaml")
    parser.add_argument("--index", default="YMGUI/CORE/YMGUI_FontDataGB2312.c")
    parser.add_argument("--char-output", default="project_Demo/chinese_ime/pinyin_gb2312.inc")
    parser.add_argument("--char-bin-output", default="project_Demo/chinese_ime/pinyin_gb2312.bin")
    parser.add_argument("--phrase-output", default="project_Demo/chinese_ime/phrases_rime.inc")
    parser.add_argument("--phrase-bin-output", default="project_Demo/chinese_ime/phrases_rime.bin")
    parser.add_argument("--phrase-limit", type=int, default=0,
                        help="maximum phrases by frequency; 0 keeps every valid phrase")
    parser.add_argument("--extra-dict", action="append", default=[],
                        help="additional word<TAB>pinyin<TAB>frequency file; repeatable")
    parser.add_argument("--english-wordlist", choices=("none", "small", "large"), default="none",
                        help="also generate an English BIN from the selected wordfreq list")
    parser.add_argument("--english-bin-output", default="project_Demo/chinese_ime/english_words.bin")
    args = parser.parse_args()
    codepoints = gb2312_codepoints(args.index)
    chars, phrases = read_rime_dictionary(args.rime_dict, codepoints)
    default_extra = Path("project_Demo/chinese_ime/user_phrases.tsv")
    extra_dictionaries = ([default_extra] if default_extra.exists() else []) + [Path(path) for path in args.extra_dict]
    for extra_dictionary in extra_dictionaries:
        read_extra_dictionary(extra_dictionary, codepoints, chars, phrases)
    chars = char_rows(chars)
    write_chars(chars, args.char_output)
    write_char_binary(chars, args.char_bin_output)
    char_count = len(chars)
    rows = phrase_rows(phrases, args.phrase_limit)
    write_phrases(rows, args.phrase_output)
    write_phrase_binary(rows, args.phrase_bin_output)
    phrase_count = len(rows)
    english_count = 0
    if args.english_wordlist != "none":
        english = english_rows(args.english_wordlist)
        write_english_binary(english, args.english_bin_output)
        english_count = len(english)
    print(f"generated {char_count} character pronunciations, {phrase_count} phrases"
          f" and {english_count} English words ({len(extra_dictionaries)} extra dictionaries)")


if __name__ == "__main__":
    main()
