#!/usr/bin/env python3
# 生成 YMGUI 内嵌位图字体数据。两种模式(字体数据是库本体,输出进 YMGUI/CORE/):
#   ASCII(默认): 定宽 8x16, 连续区间 32..126 → YMGUI/CORE/YMGUI_FontData.c (YMGUI_Font_Default)
#   CJK  (--cjk): 定宽 16x16, 稀疏排序码点表 → YMGUI/CORE/YMGUI_FontDataCJK.c (YMGUI_Font_CJK)
#
# 字集范围(方案1 精简 / 方案3 GB2312)是【本脚本】拍板的,不是 C 宏 —— 因为差别是
# "哪些汉字被烤进 .c、文件多大",属数据不属代码,预处理器变不出字模。开/关(YMGUI_FONT_CJK)
# 才是编译期宏;放内部/外部 flash 靠运行期 GYfont.glyph_read。三轴详见 YMGUI/CONFIG/YMGUI_PubDefine.h。
#
# 用法(从项目顶层跑):
#   python3 tools/gen_font.py YMGUI/CORE/YMGUI_FontData.c              # ASCII 4bpp
#   python3 tools/gen_font.py YMGUI/CORE/YMGUI_FontData.c 1            # ASCII 1bpp
#   python3 tools/gen_font.py YMGUI/CORE/YMGUI_FontDataCJK.c --cjk                  # 方案1:PRESET_CJK(~75字,9.6KB)
#   python3 tools/gen_font.py YMGUI/CORE/YMGUI_FontDataCJK.c --cjk --charset "确定取消" # 自定义字集
#   python3 tools/gen_font.py YMGUI/CORE/YMGUI_FontDataGB2312.c --cjk --gb2312 --extern --bin tools/gb2312_glyphs.bin  # 方案3:GB2312+符号(7448字形),索引进库+blob 进外部flash
#
# CJK 光栅化用 PT=16 / Y_OFF=-5 填满 16px 格高、与 ASCII 基线对齐;曾用 PT=15/Y_OFF=0
# 导致字沉底半格 + 底行被裁(现象="矮半截/少半截"),已修,见 emit_cjk。
import sys
import argparse
from PIL import Image, ImageFont, ImageDraw

ASCII_TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CJK_TTF   = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"

# demo 预置字集(方案1):够 demo_font_cjk / 常见控件标题用
PRESET_CJK = "确定取消开关亮度温度湿度设置返回主菜单音量播放暂停上下左右大小人天一二三四五六七八九十首页列表标签输入框滑块进度条中英文字体测试你好世界系统状态正常错误警告"

def load_gb2312():
    # GB2312 全集:符号/标点区(0xA1A1..0xA9FE,含中文标点 ，。！？：；、（）《》""''… 等)
    #   + 一级(3755)+二级汉字(0xB0A1..0xF7FE)。遍历高低字节解码成 Unicode。
    #   注:早期只烤汉字区(0xB0..),导致中文标点全缺(码点在 0x3000/0xFF00/0x2018 段,非汉字区)。
    chars = []
    for hi in range(0xA1, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                ch = bytes([hi, lo]).decode("gb2312")
                chars.append(ch)
            except UnicodeDecodeError:
                pass
    # 补充:输入法常打、但 GB2312 解码表不产出的符号。
    #   GB2312 的 A1AA 单元被 Python 解码成 U+2015(HORIZONTAL BAR),
    #   而中文输入法打"破折号"实际产出 U+2014(EM DASH),两者码点不同 → 不补就显示占位空格。
    #   一并补 en-dash 与间隔号(同属常用但非 GB2312 码点)。
    EXTRA = "—–·"  # — 破折号 / – 连接号 / · 间隔号
    chars.append(EXTRA)
    return "".join(chars)

def glyph_bytes(font, ch, cell_w, cell_h, bpp, bytes_per_row, y_off):
    img = Image.new("L", (cell_w, cell_h), 0)
    d = ImageDraw.Draw(img)
    d.text((0, y_off), ch, fill=255, font=font)
    px = img.load()
    rows = []
    for y in range(cell_h):
        if bpp == 1:
            for bx in range(bytes_per_row):
                b = 0
                for bit in range(8):
                    x = bx * 8 + bit
                    if x < cell_w and px[x, y] >= 128:
                        b |= (1 << (7 - bit))   # MSB 在左
                rows.append(b)
        else:  # 4bpp:每像素量化 4bit,两像素打包一字节(高 nibble 在左)
            for bx in range(bytes_per_row):
                b = 0
                for half in range(2):
                    x = bx * 2 + half
                    nib = (px[x, y] >> 4) if x < cell_w else 0  # 0..15
                    b |= nib << (4 if half == 0 else 0)
                rows.append(b)
    return rows

HDR = [
    "/**",
    "  ***************************************************************************************************************************",
    "  *\t@FileName:    {fname}",
    "  *\t@Author:      yaomimaoren (generated by tools/gen_font.py)",
    "  *\t@Date:        2026-08-01",
    "  *\t@Description: {desc}",
    "  *\t@Version:     1.0",
    "  ***************************************************************************************************************************",
    "  * Copyright (C), 2026-2036, YAOMI Tech. Co., Ltd.",
    "  ***************************************************************************************************************************/",
]
def emit_ascii(out_path, bpp):
    FIRST, LAST = 32, 126
    CELL_W, CELL_H, PT, Y_OFF = 8, 16, 15, -1
    bpr = (CELL_W * bpp + 7) // 8
    font = ImageFont.truetype(ASCII_TTF, PT)
    fname = out_path.split("/")[-1]
    desc = f"内嵌位图字体 {CELL_W}x{CELL_H} ASCII {FIRST}..{LAST} ({bpp}bpp),源自 DejaVuSansMono"
    out = ['#include "YMGUI_Font.h"', ""]
    out += [l.format(fname=fname, desc=desc) for l in HDR]
    out.append("")
    layout = "位序 MSB 在左" if bpp == 1 else "每字节2像素,高nibble在左"
    out.append(f"//每字 {CELL_H} 行 x {bpr} 字节,{bpp}bpp,{layout}")
    out.append("static const uint8 s_font_bitmap[] = {")
    #逐字形 Y 偏移例外:'_' 墨迹本在基线下方,默认 Y_OFF=-1 时整字掉出 16px 格底(全 0 不显示)。
    #单独把它上抬到 -2 拉回第 15 行即可见;其余字符保持 -1 与 CJK 基线对齐不动。
    GLYPH_Y_OFF = {ord('_'): -2}
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows = glyph_bytes(font, ch, CELL_W, CELL_H, bpp, bpr, GLYPH_Y_OFF.get(code, Y_OFF))
        hexs = ", ".join(f"0x{b:02X}" for b in rows)
        label = ch if ch != '\\' else '\\\\'
        out.append(f"\t{hexs}, //0x{code:02X} '{label}'")
    out.append("};")
    out.append("")
    # 若开 CJK,默认字体回退链指向 CJK 字体
    out.append("#include \"YMGUI_PubDefine.h\"")
    out.append("#if YMGUI_FONT_CJK")
    out.append("extern const GYfont YMGUI_Font_CJK;")
    out.append("#endif")
    out.append("")
    out.append("const GYfont YMGUI_Font_Default =")
    out.append("{")
    out.append("\ts_font_bitmap, //bitmap")
    out.append("\tNULL,          //codepoints(连续区间模式)")
    out.append("\t0,             //glyph_count")
    out.append(f"\t{FIRST},          //first_char")
    out.append(f"\t{LAST},         //last_char")
    out.append(f"\t{CELL_W},             //cell_w")
    out.append(f"\t{CELL_H},            //cell_h")
    out.append(f"\t{bpr},             //bytes_per_row")
    out.append(f"\t{bpp},             //bpp")
    out.append("#if YMGUI_FONT_CJK")
    out.append("\t&YMGUI_Font_CJK, //fallback → CJK")
    out.append("#else")
    out.append("\tNULL,          //fallback")
    out.append("#endif")
    out.append("\tNULL,          //glyph_read(内部/映射 flash,直接用指针)")
    out.append("};")
    out.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {out_path}: {LAST-FIRST+1} glyphs, {CELL_W}x{CELL_H}, {(LAST-FIRST+1)*CELL_H*bpr} bytes")


#CJK 光栅化几何(两模式共用):PT=16 填满 16px 格,Y_OFF=-5 与 ASCII 基线对齐
CJK_CELL_W, CJK_CELL_H, CJK_PT, CJK_Y_OFF = 16, 16, 16, -5


def emit_cjk(out_path, charset, bpp):
    #PT=16 填满 16px 格高(旧 PT=15/Y_OFF=0 时字沉底半格、底部还被裁,矮半截);Y_OFF=-5 抬到顶,与 ASCII 基线对齐
    CELL_W, CELL_H, PT, Y_OFF = CJK_CELL_W, CJK_CELL_H, CJK_PT, CJK_Y_OFF
    bpr = (CELL_W * bpp + 7) // 8
    font = ImageFont.truetype(CJK_TTF, PT)
    # 去重 + 只留 BMP 内(<=0xFFFF)+ 按码点排序(二分查找要求有序)
    cps = sorted({ord(c) for c in charset if 0 < ord(c) <= 0xFFFF})
    fname = out_path.split("/")[-1]
    desc = f"内嵌 CJK 位图字体 {CELL_W}x{CELL_H} ({bpp}bpp) {len(cps)} 字,稀疏码点表,源自 Noto Sans CJK SC"
    out = ['#include "YMGUI_Font.h"', ""]
    out += [l.format(fname=fname, desc=desc) for l in HDR]
    out.append("")
    out.append("#include \"YMGUI_PubDefine.h\"")
    out.append("#if YMGUI_FONT_CJK")
    out.append("")
    out.append(f"//排序码点表({len(cps)} 项,二分查找)")
    out.append("static const uint16 s_cjk_cps[] = {")
    for i in range(0, len(cps), 12):
        chunk = cps[i:i+12]
        out.append("\t" + ", ".join(f"0x{cp:04X}" for cp in chunk) + ",")
    out.append("};")
    out.append("")
    out.append(f"//每字 {CELL_H} 行 x {bpr} 字节,{bpp}bpp,每字节2像素,高nibble在左")
    out.append("static const uint8 s_cjk_bitmap[] = {")
    for cp in cps:
        ch = chr(cp)
        rows = glyph_bytes(font, ch, CELL_W, CELL_H, bpp, bpr, Y_OFF)
        hexs = ", ".join(f"0x{b:02X}" for b in rows)
        out.append(f"\t{hexs}, //U+{cp:04X} '{ch}'")
    out.append("};")
    out.append("")
    out.append("const GYfont YMGUI_Font_CJK =")
    out.append("{")
    out.append("\ts_cjk_bitmap,  //bitmap")
    out.append("\ts_cjk_cps,     //codepoints(稀疏排序)")
    out.append(f"\t{len(cps)},           //glyph_count")
    out.append("\t0,             //first_char(稀疏模式不用)")
    out.append("\t0,             //last_char")
    out.append(f"\t{CELL_W},            //cell_w")
    out.append(f"\t{CELL_H},            //cell_h")
    out.append(f"\t{bpr},             //bytes_per_row")
    out.append(f"\t{bpp},             //bpp")
    out.append("\tNULL,          //fallback(链尾)")
    out.append("\tNULL,          //glyph_read(内嵌;放外部 flash 时改这里)")
    out.append("};")
    out.append("")
    out.append("#endif // YMGUI_FONT_CJK")
    out.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {out_path}: {len(cps)} glyphs, {CELL_W}x{CELL_H}, {len(cps)*CELL_H*bpr} bytes bitmap")


def emit_cjk_extern(out_path, charset, bpp, bin_path=None):
    """外部 flash 模式:字模 bitmap 拆出去,只在 .c 里留【码点索引表 + 元信息】,
       bitmap blob 单独写 bin_path(缺省 <out_path 同名>.bin;第 i 字在 i*glyph_sz 偏移,
       即烧进外部 flash 的内容)。生成的 GYfont 不定义(app 侧自造 GYfont 字面量,填 glyph_read
       回调);此处只导出 YMGUI_GB2312_cps[] 索引 + glyph_count。"""
    CELL_W, CELL_H, PT, Y_OFF = CJK_CELL_W, CJK_CELL_H, CJK_PT, CJK_Y_OFF
    bpr = (CELL_W * bpp + 7) // 8
    glyph_sz = CELL_H * bpr
    font = ImageFont.truetype(CJK_TTF, PT)
    cps = sorted({ord(c) for c in charset if 0 < ord(c) <= 0xFFFF})
    fname = out_path.split("/")[-1]
    if bin_path is None:
        bin_path = out_path.rsplit(".", 1)[0] + ".bin"
    bin_name = bin_path.split("/")[-1]
    desc = f"GB2312 外部flash字体索引 {CELL_W}x{CELL_H} ({bpp}bpp) {len(cps)} 字。bitmap 见 {bin_name}(烧外部flash)"
    #—— 1) 索引 .c(只有码点表 + 元信息宏,无 bitmap 数组;app 用它造 GYfont)——
    out = ['#include "YMGUI_Font.h"', ""]
    out += [l.format(fname=fname, desc=desc) for l in HDR]
    out.append("")
    out.append('#include "YMGUI_PubDefine.h"')
    out.append("#if YMGUI_FONT_CJK")
    out.append("")
    out.append(f"//GB2312 排序码点表({len(cps)} 项,二分查找);字模 bitmap 不在此,存 {bin_name}")
    out.append("//每字 %d 字节(%d 行 x %d 字节),第 i 字在外部 flash 偏移 i*%d" % (glyph_sz, CELL_H, bpr, glyph_sz))
    out.append("const uint16 YMGUI_GB2312_cps[] = {")
    for i in range(0, len(cps), 12):
        chunk = cps[i:i+12]
        out.append("\t" + ", ".join(f"0x{cp:04X}" for cp in chunk) + ",")
    out.append("};")
    out.append("")
    out.append(f"//元信息(app 造 GYfont 时抄进字面量)")
    out.append(f"const uint16 YMGUI_GB2312_glyph_count = {len(cps)};")
    out.append(f"//cell_w={CELL_W} cell_h={CELL_H} bytes_per_row={bpr} bpp={bpp} glyph_sz={glyph_sz}")
    out.append("")
    out.append("#endif // YMGUI_FONT_CJK")
    out.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(out))
    #—— 2) bitmap blob .bin(纯字节,i*glyph_sz 偏移;模拟烧进外部 SPI flash 的内容)——
    with open(bin_path, "wb") as bf:
        for cp in cps:
            rows = glyph_bytes(font, chr(cp), CELL_W, CELL_H, bpp, bpr, Y_OFF)
            bf.write(bytes(rows))
    print(f"wrote {out_path}: {len(cps)} 码点索引(无bitmap)")
    print(f"wrote {bin_path}: {len(cps)*glyph_sz} bytes glyph blob (glyph_sz={glyph_sz})")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("bpp_pos", nargs="?", default=None, help="ASCII 模式位置参数 bpp(兼容旧用法)")
    ap.add_argument("--cjk", action="store_true", help="生成 CJK 字体(16x16 稀疏码点表)")
    ap.add_argument("--charset", default=PRESET_CJK, help="CJK 字集(方案1 预置,默认 demo 用字)")
    ap.add_argument("--gb2312", action="store_true", help="CJK 用 GB2312 汉字+符号全集(方案3,当前 7448 字形)")
    ap.add_argument("--extern", action="store_true",
                    help="外部flash模式:.c 只留码点索引,bitmap 另写 .bin(app 侧自造 GYfont + glyph_read 回调)")
    ap.add_argument("--bpp", type=int, default=4, help="每像素位数 1 或 4(默认 4)")
    ap.add_argument("--bin", dest="bin_path", default=None,
                    help="外部 flash blob 输出路径(缺省 <out>.bin;--extern 时用)")
    args = ap.parse_args()

    bpp = int(args.bpp_pos) if args.bpp_pos is not None else args.bpp
    if args.cjk:
        charset = load_gb2312() if args.gb2312 else args.charset
        if args.extern:
            emit_cjk_extern(args.out, charset, bpp, args.bin_path)  #方案3+外部flash:索引.c + blob.bin
        else:
            emit_cjk(args.out, charset, bpp)           #内嵌:字模烤进 .c
    else:
        emit_ascii(args.out, bpp)
